name: GHA Workflow

on:
  push:
   branches: [ debug ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Compile Code
        run: echo "Compiling..."

      - name: Produce Binary
        run: sleep 5

      - name: Push binary
        run: echo "Pushing Binary to ECR..."

      - name: Register Build Artifacts in Cloudbees Platform
        uses: cloudbees-gha-cbp/register-build-artifact@main
        id: go-action
        with:
          name: "GHA App"
          version: 1.0.3
          url: docker.io/MyApp/GHA App:1.0.3
          digest: "sha256:r5a523ee08af5e43a7fea6c4cf9c25cdf269ee113168c19722f87876677c5cb2"
          type: "docker"
          cloudbees-url: "https://api.saas-preprod.beescloud.com"
          cloudbees-pat: ${{ secrets.PREPROD_PAT }}
            
      - name: Publish evidence
        uses: cloudbees-gha-cbp/publish-evidence-item@main
        with:
          cloudbees-pat: ${{ secrets.PREPROD_PAT }}
          content: |-
            Build Completed and artifacts published to Cloudbees platform
