name: Publish evidence item
on:
  push:
   branches: [ PREPROD ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Step-1
        run: echo "hello from step 1"
        
      - uses: actions/checkout@v3

      - name: Set up environment variable for PAT
        run: echo "MY_PAT=${{ secrets.PREPROD_PAT }}"

      - name: Publish Evidence Action
        uses: cloudbees-gha-cbp/publish-evidence-item@test
        id: go-action
        with :
          cloudbees-url: "https://api.saas-preprod.beescloud.com/"
          cloudbees-pat: ${{ secrets.PREPROD_PAT }}
          content: "Test PreProd- rerun"
