name: Publish evidence item
on:
  push:
   branches: [ PREPROD ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name : Step-1
        run: echo "hello from step 1"
        
      - uses: actions/checkout@v3

      - name: Publish Evidence Action
        uses: cloudbees-gha-cbp/publish-evidence-item@CBP-14461
        id: go-action
        with :
          # cloudbees-url: "https://api.saas-preprod.beescloud.com/"
          content: "Test PreProd- OIDC"
