name: Publish evidence item
on:
  push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Step-1
        run: echo "hello from step 1"
        
      - uses: actions/checkout@v3

      - name: Set up environment variable for PAT
        run: echo "MY_PAT=${{ secrets.MY_PAT }}"

      - name: Publish Evidence Action
        uses: cloudbees-gha-cbp/publish-evidence-item@test
        # uses: akashsami4456/gha-action@main
        id: go-action
        with :
          # cloudbees-url: "https://api.saas-preprod.beescloud.com/"
          cloudbees-url: "https://api.cloudbees.io"
          cloudbees-pat: ${{ secrets.PROD_PAT }}
          content: "Test Prod"
