name: Publish evidence item
on:
  push:
   branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name : Step-1
        run: echo "hello from step 1"
        
      - name: Checkout
        uses: actions/checkout@v3

      - name: Publish Evidence Action
        uses: cloudbees-gha-cbp/publish-evidence-item@test
        id: GHA-action
        with :
          # cloudbees-url: "https://api.cloudbees.io"
          cloudbees-pat: ${{ secrets.PROD_PAT }}
          content: "Evidence : Demo"
